"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Bot,Check,ChevronLeft,ChevronRight,Clipboard,Code2,Eye,FileCheck2,KeyRound,LockKeyhole,Network,Play,ShieldCheck,Terminal,Workflow} from "lucide-react";
type Agent={external_id:string;name:string;status:string;authority_scope:string[]};
const steps=["Register","Authority","Credential","Integrate","Test","Complete"];
export default function IntegratePage(){
 const [agents,setAgents]=useState<Agent[]>([]),[step,setStep]=useState(0),[externalId,setExternalId]=useState("finance-agent"),[name,setName]=useState("Finance Agent"),[description,setDescription]=useState("Autonomous agent for invoice processing, payments, and financial reporting."),[environment,setEnvironment]=useState("Production"),[scope,setScope]=useState<string[]>(["invoices.read","payments.create","payments.submit"]),[secret,setSecret]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[check,setCheck]=useState<any>(null),[decision,setDecision]=useState<any>(null);
 const agent=useMemo(()=>agents.find(a=>a.external_id===externalId)||agents[0],[agents,externalId]);
 async function load(){const r=await fetch("/api/integrations/agents");if(r.status===401){location.href="/auth/github";return}if(r.ok){const j=await r.json();setAgents(j.agents??[])}}
 useEffect(()=>{void load()},[]);
 const toggle=(v:string)=>setScope(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v]);
 async function register(){setBusy(true);setMsg("");const r=await fetch("/api/integrations/agents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({externalId,name,authorityScope:scope})});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error??"Could not register agent");return}await load();setStep(1)}
 async function saveAuthority(){if(!agent){setStep(0);return}setBusy(true);const r=await fetch("/api/integrations/agents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:agent.external_id,authorityScope:scope})});setBusy(false);if(!r.ok){setMsg("Could not save authority");return}await load();setStep(2)}
 async function credential(){if(!agent)return;setBusy(true);const r=await fetch("/api/integrations/credentials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:agent.external_id,label:"Primary integration"})});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error??"Could not create credential");return}setSecret(j.secret);setStep(2)}
 async function testConnection(){if(!agent)return;setBusy(true);const r=await fetch("/api/integrations/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:agent.external_id})});const j=await r.json();setBusy(false);setCheck(j);if(j.connected)setStep(5)}
 const snippet='import { Nodra } from "@nodra/sdk";\n\nconst nodra = new Nodra({\n  baseUrl: process.env.NODRA_BASE_URL!,\n  credential: process.env.NODRA_CREDENTIAL!\n});\n\nconst agent = nodra.protect({ id: "'+(agent?.external_id||externalId)+'" });';
 async function firstAction(){if(!agent){setMsg("Register your agent first.");return}setBusy(true);const r=await fetch("/api/integrations/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:agent.external_id})});const j=await r.json();setBusy(false);setDecision(j);if(j.connected)setStep(5);else setMsg("Run your integrated agent once so Nodra receives a signed protected action.")}
 return <main className="wizardPage"><header className="wizardTop"><Link href="/"><img src="/nodra-logo.webp" alt="Nodra"/><b>NODRA</b></Link><Link href="/docs">ⓘ Help</Link></header><div className="wizardShell">
 <div className="wizardSteps">{steps.map((s,i)=><div key={s} className={i===step?"active":i<step?"done":""}><span>{i<step?<Check/>:i+1}</span><small>{s}</small>{i<steps.length-1&&<i/>}</div>)}</div>
 {step===0&&<section className="wizardCard registerStep"><div><h1>Register Your Agent</h1><p>Tell us about your agent.</p><label>Agent Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="fieldRow"><label>Agent ID<input value={externalId} onChange={e=>setExternalId(e.target.value)} pattern="[A-Za-z0-9_-]{2,64}"/></label><label>Environment<select value={environment} onChange={e=>setEnvironment(e.target.value)}><option>Production</option><option>Staging</option><option>Development</option></select></label></div></div><div className="agentAvatar"><span><Bot/></span><small>Protected agent identity</small></div><footer><Link href="/network">Cancel</Link><button onClick={register} disabled={busy}>Next <ChevronRight/></button></footer></section>}
 {step===1&&<section className="wizardCard authorityStep"><h1>Define Authority</h1><p>Set what this agent is allowed to do.</p><div className="authorityTabs"><b>Templates</b><span>Custom</span></div>{[["invoices.read","Read invoices"],["payments.create","Create payments"],["payments.submit","Submit payments"],["bank.accounts","Access bank accounts"],["data.export","Export financial data"]].map(([v,l])=><label className="scopeLine" key={v}><input type="checkbox" checked={scope.includes(v)} onChange={()=>toggle(v)}/><strong>{l}</strong><code>{v}</code></label>)}<footer><button className="back" onClick={()=>setStep(0)}><ChevronLeft/> Back</button><button onClick={saveAuthority} disabled={busy}>Next <ChevronRight/></button></footer></section>}
 {step===2&&<section className="wizardCard credentialStep"><h1>Generate Integration Credential</h1><p>This credential allows your agent to securely connect to Nodra.</p><div className="credentialBox"><label>Agent ID<div className="copyField"><code>{agent?.external_id||externalId}</code><Clipboard/></div></label>{secret?<><label>Client Secret<div className="copyField secretField"><code>{secret}</code><button onClick={()=>navigator.clipboard.writeText(secret)}><Clipboard/></button></div></label><div className="secretWarning">⚠ This secret will only be shown once. Store it securely.</div></>:<button onClick={credential} disabled={busy}><KeyRound/> Generate Credential</button>}</div><footer><button className="back" onClick={()=>setStep(1)}><ChevronLeft/> Back</button><button onClick={()=>secret&&setStep(3)} disabled={!secret}>Next <ChevronRight/></button></footer></section>}
 {step===3&&<section className="wizardCard integrationStep"><h1>Choose Your Integration Method</h1><p>Select how you want to connect your agent.</p><div className="methodTabs"><b>JavaScript / TypeScript</b><span>Python</span><span>REST API</span><span>MCP</span></div><label>Install the SDK<div className="copyField"><code>npm install @nodra/sdk</code><Clipboard/></div></label><label>Initialize and protect your agent</label><pre>{snippet}</pre><small className="releaseNote">Use the repository SDK until public registry release is verified.</small><footer><button className="back" onClick={()=>setStep(2)}><ChevronLeft/> Back</button><button onClick={()=>setStep(4)}>Next <ChevronRight/></button></footer></section>}
 {step===4&&<section className="wizardCard testStep"><h1>Test Connection</h1><p>Let's verify your agent is connected to Nodra.</p><button className="testButton" onClick={testConnection} disabled={busy}><Play/> Test Connection</button>{check&&<div className={check.connected?"testResult success":"testResult"}><span>{check.connected?<Check/>:<Network/>}</span><div><strong>{check.connected?"Connection successful!":"Waiting for protected runtime"}</strong><p>{check.message}</p></div></div>}<div className="checkGrid"><span><ShieldCheck/> Credential {check?.checks?.activeCredential?"✓":"—"}</span><span><KeyRound/> Used {check?.checks?.credentialUsed?"✓":"—"}</span><span><FileCheck2/> Evidence {check?.checks?.runtimeEvidence?"✓":"—"}</span><span><LockKeyhole/> Authority {check?.checks?.authorityConfigured?"✓":"—"}</span></div><footer><button className="back" onClick={()=>setStep(3)}><ChevronLeft/> Back</button><button onClick={()=>setStep(5)} disabled={!check?.connected}>Next <ChevronRight/></button></footer></section>}
 {step===5&&<section className="wizardCard completeStep"><div className="successOrb"><Check/></div><h1>Your agent is protected!</h1><p>You've successfully registered and connected your first agent. You can now manage all your agents from the dashboard.</p><Link className="wizardPrimaryLink" href="/network">Go to Dashboard <ChevronRight/></Link><button onClick={()=>{setStep(0);setSecret("");setCheck(null);setExternalId("new-agent");setName("New Agent")}}>Add Another Agent</button></section>}
 {msg&&<div className="wizardMessage">{msg}</div>}</div></main>
}