import { GitHubAuthButton } from "../components/github-auth-button";
import { ShieldCheck, ShieldAlert, Eye, Network, Siren, FileCheck2, Code2, Building2, Users, CheckCircle2, LockKeyhole, Database, Workflow, Boxes, ArrowRight } from "lucide-react";

const features=[
  {n:"01",icon:ShieldCheck,title:"Enforce authority",body:"Put a deterministic boundary between agent intent and consequential action.",tag:"CONTROL"},
  {n:"02",icon:Eye,title:"See every action",body:"Turn protected runtime activity into high-signal, workspace-scoped evidence.",tag:"OBSERVE"},
  {n:"03",icon:Network,title:"Trace causality",body:"Follow relationships between agents, resources, incidents and the actions that connected them.",tag:"TRACE"},
  {n:"04",icon:Siren,title:"Contain impact",body:"Move from suspicious behavior to containment and controlled recovery without losing context.",tag:"RESPOND"},
  {n:"05",icon:FileCheck2,title:"Require approval",body:"Hold sensitive actions at the boundary and bind human decisions to the exact authorization event.",tag:"GOVERN"},
  {n:"06",icon:Boxes,title:"Integrate cleanly",body:"Protect existing agent runtimes through signed APIs and SDK-level enforcement points.",tag:"BUILD"}
];

export default function HomePage(){return <main className="refHome" id="top">
  <header className="refNav refShell"><a className="skipHome" href="#main-content">Skip to content</a>
    <a className="refBrand" href="#top" aria-label="Nodra home"><span className="refBrandGlyph" aria-hidden="true"><i/><i/></span><b>NODRA</b></a>
    <nav aria-label="Primary navigation"><a href="#product">Product</a><a href="#solutions">Solutions</a><a href="#developers">Developers</a><a href="#security">Security</a><a href="/docs">Resources</a></nav>
    <div className="refNavActions"><GitHubAuthButton className="refSign">Sign in</GitHubAuthButton><GitHubAuthButton className="refPrimary">Get Started <ArrowRight/></GitHubAuthButton></div>
  </header>

  <section className="refHero refShell" id="main-content">
    <div className="refHeroCopy">
      <span className="refEyebrow"><i/> THE CONTROL LAYER FOR AGENTIC AI</span>
      <h1>Give AI agents<br/><span>freedom to act.</span><br/><em>Keep control.</em></h1>
      <p>Nodra is the security control plane between autonomous agents and the systems they can change — identity, authority, policy, evidence and recovery in one trusted layer.</p>
      <div className="refHeroButtons"><GitHubAuthButton className="refPrimary big">Get Started for Free <ArrowRight/></GitHubAuthButton><a className="refOutline" href="/docs">View Documentation</a></div>
      <div className="refChecks"><span><i/> Identity-bound</span><span><i/> Policy-enforced</span><span><i/> Evidence-preserving</span></div><div className="heroSignal"><span>AGENT</span><i/><b>NODRA CONTROL PLANE</b><i/><span>TOOLS & SYSTEMS</span></div>
    </div>
    <div className="refRobot" aria-label="Nodra autonomous agent security">
      <div className="refPlanet"/>
      <div className="refBot" aria-hidden="true"><div className="botAntenna"/><div className="botHelmet"><span className="botTempleMark">N</span><span className="botFaceplate"/><i className="botEye"/><span className="botCheek"/><span className="botJaw"/></div><div className="botNeck"/><div className="botShoulder left"/><div className="botShoulder right"/><div className="botBody"><span className="botChestMark">N</span></div></div>
      <div className="refHeroStatement"><small>AUTONOMY WITHOUT BLIND TRUST</small>AI AGENTS<br/>DESERVE<br/><strong>REAL CONTROL</strong></div>
      <div className="refPills"><span>Identity</span><i/> <span>Authority</span><i/> <span>Control</span><i/> <span>Evidence</span></div>
      <div className="refMiniConsole"><div className="miniTop"><b><ShieldCheck/> NODRA</b><span><i/> LIVE CONTROL PLANE</span></div><div className="miniGrid"><div><small>IDENTITY</small><strong>Verified</strong></div><div><small>AUTHORITY</small><strong>Enforced</strong></div><div><small>EVIDENCE</small><strong>Preserved</strong></div></div><div className="miniGraph"><i/><i/><i/><i/><i/><i/></div></div>
    </div>
  </section>

  <section className="refTrust"><div className="refShell"><span>SECURITY CONTROL LAYERS</span><b>Identity</b><b>Authority</b><b>Policy</b><b>Evidence</b><b>Containment</b><b>Recovery</b><strong>BUILD A SAFER<br/>AI FUTURE</strong></div></section>

  <section className="refProduct refShell" id="product"><div className="refSectionIntro"><div><span className="refEyebrow"><i/> THE SECURITY CONTROL PLANE</span><h2>Autonomy needs<br/><em>boundaries that hold.</em></h2></div><p>Prompts can guide an agent. Nodra is designed to enforce what happens when that agent reaches for a real tool, API, database or system.</p></div><div className="refFeatures">{features.map(({n,icon:Icon,title,body,tag})=><article key={title}><div className="featureTop"><span className="featureIcon"><Icon/></span><small>{n}</small></div><span className="featureTag">{tag}</span><h3>{title}</h3><p>{body}</p><div className="featureLine"><i/><span/></div></article>)}</div><div className="refBoundary"><span>AGENT INTENT</span><i/><b><ShieldCheck/> NODRA ENFORCEMENT BOUNDARY</b><i/><span>CONSEQUENTIAL ACTION</span></div></section>

  <section className="refHow" id="security"><div className="refShell howInner"><div className="howCopy"><span className="refEyebrow"><i/> HOW NODRA WORKS</span><h2>One decision boundary.<br/><em>Every consequential action.</em></h2><p>An agent can reason freely. The moment it reaches for a protected resource, Nodra verifies the runtime identity, evaluates authority, records the decision and preserves the evidence.</p><div className="howSteps">
    <div><small>01</small><span><Users/></span><b>Agent intent</b><p>A protected agent requests a real action.</p></div><i/>
    <div><small>02</small><span><LockKeyhole/></span><b>Verify identity</b><p>Signed runtime credentials bind the request.</p></div><i/>
    <div><small>03</small><span><FileCheck2/></span><b>Enforce authority</b><p>Scope and policy determine the boundary.</p></div><i/>
    <div><small>04</small><span className="green"><CheckCircle2/></span><b>Decide</b><p>Allow, deny, or require human approval.</p></div><i/>
    <div><small>05</small><span><Database/></span><b>Preserve evidence</b><p>The outcome enters the security evidence chain.</p></div>
  </div></div><div className="riskVisual"><div className="riskGrid"/><div className="riskOrbit one"/><div className="riskOrbit two"/><div className="riskOrb"><ShieldCheck/><span>NODRA</span><small>ENFORCEMENT</small></div><div className="riskNode agent"><Users/><span>AGENT</span></div><div className="riskNode tool"><Workflow/><span>TOOL</span></div><div className="riskNode evidence"><Database/><span>EVIDENCE</span></div><div className="riskPulse"/><div className="riskCard"><small>CONTROL STATE</small><b><i/> ENFORCING</b><span>Identity verified · authority checked</span></div></div></div></section>

  <section className="refDevelopers refShell" id="developers">
    <div className="devCopy"><span className="refEyebrow"><i/> FOR DEVELOPERS</span><h2>Protect the action.<br/><em>Keep your stack.</em></h2><p>Nodra is designed to sit at the enforcement point in an existing agent runtime. Start with the repository SDK today or integrate directly with the signed REST boundary.</p><div className="devSignals"><span><ShieldCheck/> Signed requests</span><span><LockKeyhole/> Server-side credentials</span><span><FileCheck2/> Typed decisions</span></div><a className="devDocsLink" href="/docs">Open developer documentation <ArrowRight/></a></div>
    <div className="devWorkbench"><div className="workbenchTop"><div><i/><i/><i/></div><span>protect-agent.ts</span><small>QUICKSTART</small></div><div className="codeHead"><b>TypeScript</b><span>Python</span><span>REST</span><span>MCP</span></div><pre><code><span className="codeDim">{"// Bind Nodra to a runtime identity"}</span>{"\n"}<span className="codeBlue">const</span> agent = nodra.protect({"{"} id: <span className="codeGreen">"finance-agent"</span> {"}"});{"\n\n"}<span className="codeBlue">const</span> decision = <span className="codeBlue">await</span> agent.authorize({"{"}{"\n  "}resourceId: <span className="codeGreen">"payments"</span>,{"\n  "}action: <span className="codeGreen">"send_payment"</span>{"\n"}{"}"});{"\n\n"}<span className="codeBlue">if</span> (decision.decision !== <span className="codeGreen">"allow"</span>) stop();</code></pre><div className="workbenchResult"><span><i/> AUTHORIZATION</span><b>ALLOW</b><small>Evidence preserved</small></div><footer><span>Repository SDK available now</span><a href="/docs">Integration guide <ArrowRight/></a></footer></div>
    <div className="devArchitecture"><div className="devArchHead"><span>INTEGRATION SURFACE</span><b>One boundary. Multiple runtimes.</b></div><div className="devArchGrid"><span><Code2/><b>SDK</b><small>Application runtime</small></span><i/><span><Workflow/><b>Signed REST</b><small>Language agnostic</small></span><i/><span><Boxes/><b>MCP guard</b><small>Tool boundary</small></span></div><div className="devArchFoot"><ShieldCheck/><span>Nodra evaluates identity, authority and policy before the protected action crosses the boundary.</span></div></div>
  </section>

  <section className="refTeams refShell" id="solutions">
    <div className="teamsIntro"><span className="refEyebrow"><i/> BUILT FOR OPERATORS</span><h2>Control for the teams<br/><em>responsible when agents act.</em></h2><p>Security teams need visibility and intervention. Organizations need enforceable boundaries and accountable operations. Nodra brings both into one control plane.</p></div>
    <div className="teamPanels">
      <article className="teamPanel securityTeam"><div className="teamPanelTop"><span><ShieldAlert/></span><small>SECURITY OPERATIONS</small></div><h3>See risk before it becomes impact.</h3><p>Investigate protected runtime activity, hold sensitive actions for review, contain incidents and preserve the evidence needed to reconstruct what happened.</p><div className="teamChecks"><span><i/> Human approval gates</span><span><i/> Incident containment</span><span><i/> Causal investigation</span><span><i/> Tamper-evident activity</span></div><a className="teamAction" href="#security">Explore the security model <ArrowRight/></a></article>
      <article className="teamPanel orgTeam"><div className="teamPanelTop"><span><Building2/></span><small>ORGANIZATION CONTROL</small></div><h3>Give every agent an explicit operating boundary.</h3><p>Separate workspaces, bind runtime identities, scope authority and keep high-impact actions subject to deterministic controls instead of model judgment alone.</p><div className="teamChecks"><span><i/> Workspace isolation</span><span><i/> Explicit authority</span><span><i/> Role-aware administration</span><span><i/> Controlled recovery</span></div><GitHubAuthButton className="teamAction">Set up a workspace <ArrowRight/></GitHubAuthButton></article>
    </div>
    <aside className="securitySpine"><div className="spineMark"><ShieldCheck/><i/></div><div><small>SECURITY SPINE</small><h3>Identity → Authority → Decision → Evidence → Response</h3><p>The same boundary that authorizes an action also gives operators the context to investigate, contain and recover.</p></div><div className="spineSignals"><span><LockKeyhole/> Least privilege</span><span><Users/> Human oversight</span><span><Database/> Evidence chain</span></div><a href="/docs">Security model <ArrowRight/></a></aside>
  </section>

  <section className="refFinal"><div className="finalAtmosphere"><i/><i/><i/></div><div className="mountains"/><div className="refShell finalInner"><span className="refEyebrow"><i/> BUILD WITH CONTROL</span><h2>Let agents move fast.<br/><em>Keep authority with you.</em></h2><p>Put a security boundary between autonomous intent and the systems that matter.</p><div className="finalActions"><GitHubAuthButton className="refPrimary">Protect your first agent <ArrowRight/></GitHubAuthButton><a className="refOutline" href="/docs">Explore the security model</a></div><div className="finalProof"><span><ShieldCheck/> Identity-bound</span><span><LockKeyhole/> Least privilege</span><span><Database/> Evidence-preserving</span></div></div></section>

  <footer className="refFooter"><div className="refShell footerGrid"><div className="footerBrand"><a className="refBrand" href="#top" aria-label="Nodra home"><span className="refBrandGlyph" aria-hidden="true"><i/><i/></span><b>NODRA</b></a><p>The security control plane for agentic AI.</p><span className="footerStatus"><i/> SYSTEM SURFACE ONLINE</span></div><div><b>Product</b><a href="#product">Capabilities</a><a href="#security">How it works</a><a href="#solutions">Security teams</a></div><div><b>Developers</b><a href="/docs">Documentation</a><a href="#developers">Integration</a><a href="/docs">API reference</a></div><div><b>Security</b><a href="#security">Control model</a><a href="#solutions">Human oversight</a><a href="/docs">Security model</a></div><div><b>Start</b><GitHubAuthButton className="footerButton">Create workspace</GitHubAuthButton><a href="/auth/github">Sign in</a></div></div><div className="refShell footerBottom"><span>© 2026 Nodra. All rights reserved.</span><b>IDENTITY · AUTHORITY · CONTROL · EVIDENCE</b><a href="#top">Back to top ↑</a></div></footer>
</main>}