import { GitHubAuthButton } from "../components/github-auth-button";

const capabilities=[
["shield","Permission Control","Define what your agents can access and do."],
["eye","Real-time Monitoring","Track consequential actions and security events."],
["trace","Provenance & Trace","Follow authority and action paths across agent networks."],
["alert","Threat Containment","Isolate affected agents before incidents spread."],
["recover","Safe Recovery","Review recovery state and restart operations safely."]
];
export default function HomePage(){return <main className="devHome">
<header className="devNav shell"><a className="devBrand" href="#top"><img src="/nodra-logo.png" alt="Nodra — The Shield for Agentic AI"/></a><nav><a href="#product">Product</a><a href="#developers">Developers</a><a href="#docs">Documentation</a><a href="#security">Security</a></nav><div className="devNavActions"><GitHubAuthButton className="devSign">Sign in</GitHubAuthButton><GitHubAuthButton className="devPrimary small">Get started</GitHubAuthButton></div></header>
<section className="devHero shell" id="top"><div className="heroText"><div className="devPill">SECURITY INFRASTRUCTURE FOR AUTONOMOUS AGENTS</div><h1>A safer foundation<br/>for <em>agentic AI.</em></h1><p>Nodra provides security, control, and observability for AI agents that can take real actions. Enforce permissions, record consequential actions, trace propagation, contain affected agents, and recover safely.</p><div className="devHeroActions"><GitHubAuthButton className="devPrimary">Get started <b>→</b></GitHubAuthButton><a className="devSecondary" href="#docs">Read the documentation</a></div><small>Built for controlled, observable agent operations.</small></div><div className="heroVisual"><div className="halo"/><img src="/nodra-logo.png" alt="Nodra"/><div className="heroWords">SECURE<br/>CONTROLLED<br/>OBSERVABLE<br/>RESILIENT</div></div></section>
<section className="integration shell" id="developers"><div className="integrationMain"><h2>Start integrating</h2><p>Use Nodra with your preferred environment.</p><div className="sdkTabs"><span className="active">JavaScript / TypeScript</span><span>Python</span><span>REST API</span></div><div className="installLine"><code>npm install @nodra/sdk</code><button aria-label="Copy install command">⧉</button></div><a href="#docs" className="inlineLink">View JavaScript quickstart →</a></div><aside><h3>Developer resources</h3><a href="#docs">▣ &nbsp; Installation guides</a><a href="#docs">◇ &nbsp; API reference</a><a href="#docs">▤ &nbsp; Examples and tutorials</a><a href="https://github.com/Only-time-hash/Nodra">⌘ &nbsp; Source on GitHub</a></aside></section>
<section className="capSection shell" id="product"><div className="sectionHead"><div><h2>Core capabilities</h2><p>Security controls for agent systems from development through operation.</p></div><a href="#security">Explore capabilities →</a></div><div className="capGrid">{capabilities.map(([icon,title,body])=><article key={title} className={"cap "+icon}><i/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="how shell" id="security"><div className="howMain"><h2>How Nodra works</h2><p>A security layer between your agents and consequential tools.</p><div className="flow"><div className="flowBox">◎<span>AI Agent<small>your application</small></span></div><b>→</b><div className="flowBox gateway"><img src="/nodra-logo.png" alt=""/><span>NODRA GATEWAY<small>Identity · Policy · Security</small></span></div><b>→</b><div className="flowBox">◉<span>Tools / APIs / Databases</span></div></div><div className="decisions"><div>✓ <span>Allow</span></div><div>⊘ <span>Block</span></div><div>◷ <span>Require approval</span></div></div><div className="evidence">▤ &nbsp; <strong>Audit & Evidence</strong><small>Recorded security events and provenance</small></div></div><aside><h2>Built for real-world use</h2><ul><li>Explicit agent authority boundaries</li><li>Policy-gated consequential actions</li><li>Traceable security evidence</li><li>Selective incident containment</li><li>Reviewable recovery workflow</li><li>JavaScript and Python SDK workspaces</li></ul><a href="#docs" className="devSecondary">Learn more →</a></aside></section>
<section className="devCta" id="docs"><div className="shell ctaInner"><div><h2>Build the next generation of AI agents safely.</h2><p>Integrate Nodra, define explicit boundaries, and keep consequential agent actions observable.</p><div className="devHeroActions"><GitHubAuthButton className="devPrimary">Get started →</GitHubAuthButton><a className="devSecondary" href="https://github.com/Only-time-hash/Nodra">View source</a></div></div><div className="openSource"><strong>Built in public.<br/>Built for what's next.</strong><p>Explore the source and follow Nodra's development.</p><a href="https://github.com/Only-time-hash/Nodra">View on GitHub →</a></div></div></section>
<footer className="devFooter shell"><a className="devBrand" href="#top"><img src="/nodra-logo.png" alt="Nodra"/></a><div><a href="#product">Product</a><a href="#developers">Developers</a><a href="#docs">Documentation</a><a href="#security">Security</a></div><p>© 2026 Nodra.</p></footer></main>}