import { GitHubAuthButton } from "../components/github-auth-button";
import { IntegrationChooser } from "./components/integration-chooser";

const capabilities=[
["shield","Permission Control","Define what your agents can access and do."],
["eye","Real-time Monitoring","Track consequential actions and security events."],
["trace","Provenance & Trace","Follow authority and action paths across agent networks."],
["alert","Threat Containment","Isolate affected agents before incidents spread."],
["recover","Safe Recovery","Review recovery state and restart operations safely."]
];
export default function HomePage(){return <main className="devHome">
<header className="devNav shell"><a className="devBrand" href="#top"><img src="/nodra-logo.png" alt="Nodra — The Shield for Agentic AI"/></a><nav><a href="#product">Product</a><a href="#developers">Developers</a><a href="#docs">Documentation</a><a href="#security">Security</a></nav><div className="devNavActions"><GitHubAuthButton className="devSign">Sign in</GitHubAuthButton><GitHubAuthButton className="devPrimary small">Get started</GitHubAuthButton></div></header>
<section className="devHero shell" id="top"><div className="heroText"><div className="devPill">SECURITY INFRASTRUCTURE FOR AUTONOMOUS AGENTS</div><h1>A safer foundation<br/>for <em>agentic AI.</em></h1><p>Nodra provides security, control, and observability for AI agents that can take real actions. Enforce permissions, record consequential actions, trace propagation, contain affected agents, and recover safely.</p><div className="devHeroActions"><GitHubAuthButton className="devPrimary">Get started <b>→</b></GitHubAuthButton><a className="devSecondary" href="#docs">Read the documentation</a></div><small>Built for controlled, observable agent operations.</small></div><div className="heroVisual"><div className="halo"/><img src="/nodra-logo.png" alt="Nodra"/><div className="heroWords">SECURE<br/>CONTROLLED<br/>OBSERVABLE<br/>RESILIENT</div></div></section>
<section className="integration shell" id="developers"><div className="integrationMain"><h2>Start integrating</h2><p>Use Nodra with your preferred environment.</p><IntegrationChooser/></div><aside><h3>Developer resources</h3><a href="#docs">▣ &nbsp; Installation guides</a><a href="#docs">◇ &nbsp; API reference</a><a href="#docs">▤ &nbsp; Examples and tutorials</a><a href="https://github.com/Only-time-hash/Nodra">⌘ &nbsp; Source on GitHub</a></aside></section>
<section className="capSection shell" id="product"><div className="sectionHead"><div><h2>Core capabilities</h2><p>Security controls for agent systems from development through operation.</p></div><a href="#security">Explore capabilities →</a></div><div className="capGrid">{capabilities.map(([icon,title,body])=><article key={title} className={"cap "+icon}><i/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="how shell" id="security"><div className="howMain"><h2>How Nodra works</h2><p>A security layer between your agents and consequential tools.</p><div className="flow"><div className="flowBox">◎<span>AI Agent<small>your application</small></span></div><b>→</b><div className="flowBox gateway"><img src="/nodra-logo.png" alt=""/><span>NODRA GATEWAY<small>Identity · Policy · Security</small></span></div><b>→</b><div className="flowBox">◉<span>Tools / APIs / Databases</span></div></div><div className="decisions"><div>✓ <span>Allow</span></div><div>⊘ <span>Block</span></div><div>◷ <span>Require approval</span></div></div><div className="evidence">▤ &nbsp; <strong>Audit & Evidence</strong><small>Recorded security events and provenance</small></div></div><aside><h2>Built for real-world use</h2><ul><li>Explicit agent authority boundaries</li><li>Policy-gated consequential actions</li><li>Traceable security evidence</li><li>Selective incident containment</li><li>Reviewable recovery workflow</li><li>JavaScript and Python SDK workspaces</li></ul><a href="#docs" className="devSecondary">Learn more →</a></aside></section>
<section className="docsHome shell" id="documentation"><div><p className="kicker">DOCUMENTATION</p><h2>Build with Nodra</h2><p>Start with the SDK workspaces, understand the gateway and policy model, then connect agent actions to Nodra security controls.</p></div><div className="docsCards"><article><strong>01</strong><h3>Quickstarts</h3><p>JavaScript / TypeScript, Python, and REST integration paths.</p><a href="#developers">Choose an integration →</a></article><article><strong>02</strong><h3>Gateway & policy</h3><p>Learn how actions are authorized, denied, or routed for approval.</p><a href="#security">See the architecture →</a></article><article><strong>03</strong><h3>Security model</h3><p>Understand provenance, containment, evidence, and recovery.</p><a href="#security">Explore security →</a></article></div></section><section className="devCta" id="docs"><div className="shell ctaInner"><div><h2>Build the next generation of AI agents safely.</h2><p>Integrate Nodra, define explicit boundaries, and keep consequential agent actions observable.</p><div className="devHeroActions"><GitHubAuthButton className="devPrimary">Get started →</GitHubAuthButton><a className="devSecondary" href="https://github.com/Only-time-hash/Nodra">View source</a></div></div><div className="openSource"><strong>Built in public.<br/>Built for what's next.</strong><p>Explore the source and follow Nodra's development.</p><a className="githubButton" href="https://github.com/Only-time-hash/Nodra" aria-label="View Nodra on GitHub"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .7a11.5 11.5 0 0 0-3.64 22.41c.58.1.79-.25.79-.56v-2.02c-3.22.7-3.9-1.37-3.9-1.37-.53-1.34-1.29-1.7-1.29-1.7-1.05-.72.08-.7.08-.7 1.17.08 1.78 1.2 1.78 1.2 1.04 1.78 2.72 1.27 3.38.97.1-.75.4-1.27.74-1.56-2.57-.29-5.27-1.29-5.27-5.69 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.47.11-3.06 0 0 .97-.31 3.16 1.18A10.9 10.9 0 0 1 12 6.31c.98 0 1.95.13 2.87.39 2.19-1.49 3.15-1.18 3.15-1.18.63 1.59.23 2.77.11 3.06.74.81 1.19 1.84 1.19 3.1 0 4.42-2.71 5.39-5.29 5.68.42.36.79 1.07.79 2.16v3.03c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z"/></svg><span>View on GitHub</span></a></div></div></section>
<footer className="devFooter shell"><a className="devBrand" href="#top"><img src="/nodra-logo.png" alt="Nodra"/></a><div><a href="#product">Product</a><a href="#developers">Developers</a><a href="#docs">Documentation</a><a href="#security">Security</a></div><p>© 2026 Nodra.</p></footer></main>}