"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Bot,ChevronRight,PauseCircle,Plus,ShieldCheck} from "lucide-react";
type Agent={id:string;external_id:string;name:string;kind:string;status:string;authority_scope:string[]};
export default function AgentsPage(){
 const [agents,setAgents]=useState<Agent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/integrations/agents",{cache:"no-store"});if(r.status===401){location.href="/auth/github";return}const j=await r.json();if(!r.ok)setError(j.error??"Could not load agents");else setAgents((j.agents??[]).filter((a:Agent)=>a.kind==="customer"));setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function pause(externalId:string){if(!confirm("Pause this agent? Nodra will treat it as unavailable until it is re-enabled."))return;setBusy(externalId);const r=await fetch("/api/integrations/agents",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({externalId})});const j=await r.json();setBusy("");if(!r.ok){setError(j.error??"Could not pause agent");return}await load()}
 return <main className="agentsPage"><header className="credentialTop"><Link href="/network"><span className="refBrandGlyph" aria-hidden="true"><i/><i/></span><b>NODRA</b></Link><nav><Link href="/network">Dashboard</Link><Link href="/credentials">Credentials</Link></nav></header><section className="agentsShell"><div className="credentialHeading"><div><span>AGENT CONTROL</span><h1>Protected Agents</h1><p>Real customer agents registered in this workspace. Laboratory agents are kept separate.</p></div><Link className="credentialAdd" href="/onboarding/integrate"><Plus/> Protect Agent</Link></div>{error&&<div className="credentialError">{error}</div>}<div className="agentCards">{loading?<div className="credentialEmpty">Loading protected agents…</div>:agents.length===0?<div className="credentialEmpty"><Bot/><strong>No customer agents registered</strong><p>Protect your first production or development agent through the integration flow.</p><Link href="/onboarding/integrate">Register agent</Link></div>:agents.map(a=><article className="agentCard" key={a.id}><div className="agentCardIcon"><Bot/></div><div className="agentCardMain"><div><h2>{a.name}</h2><code>{a.external_id}</code></div><span className={"agentState "+a.status}>{a.status}</span></div><div className="agentAuthority"><small>AUTHORITY</small>{a.authority_scope?.length?<div>{a.authority_scope.slice(0,5).map(s=><span key={s}>{s}</span>)}{a.authority_scope.length>5&&<span>+{a.authority_scope.length-5}</span>}</div>:<p>No authority configured</p>}</div><footer><Link href="/activity">View activity <ChevronRight/></Link>{a.status!=="paused"&&<button disabled={busy===a.external_id} onClick={()=>pause(a.external_id)}><PauseCircle/> Pause agent</button>}</footer></article>)}</div><aside className="credentialSafety"><ShieldCheck/><div><strong>Enforcement boundary</strong><p>Agent status and authority are evaluated by Nodra before protected actions. Paused agents must not be allowed to execute through the protected runtime.</p></div></aside></section></main>