"use client";
import {useState} from "react";
import Link from "next/link";
export default function ConnectAgent(){
 const [step,setStep]=useState(1),[agentId,setAgentId]=useState(""),[name,setName]=useState(""),[method,setMethod]=useState("node"),[credential,setCredential]=useState(""),[message,setMessage]=useState(""),[connected,setConnected]=useState(false),[scope,setScope]=useState("read");
 async function register(){setMessage("Registering…");const r=await fetch("/api/integrations/agents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({externalId:agentId,name,authorityScope:[]})});const j=await r.json();if(!r.ok)return setMessage(j.error||"Registration failed");setStep(2);setMessage("")}
 async function issue(){setMessage("Generating credential…");const r=await fetch("/api/integrations/credentials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId,label:"Primary integration"})});const j=await r.json();if(!r.ok)return setMessage(j.error||"Credential failed");setCredential(j.secret);setStep(4);setMessage("")}
 async function saveAuthority(){const values=scope.split(",").map(v=>v.trim()).filter(Boolean);setMessage("Saving authority…");const r=await fetch("/api/integrations/agents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({externalId:agentId,authorityScope:values})});const j=await r.json().catch(()=>({}));if(!r.ok)return setMessage(j.error||"Authority update failed");setMessage("Authority saved");}
 async function verify(){setMessage("Checking signed runtime traffic…");const r=await fetch("/api/integrations/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId})});const j=await r.json().catch(()=>({}));setConnected(Boolean(r.ok&&j.connected));setMessage(r.ok&&j.connected?"Protection verified":"No signed runtime event received yet. Send one from the installed SDK or Gateway, then retry.");}
 const install=method==="node"?"npm install @nodra/sdk":method==="python"?"pip install nodra":"docker build -f deploy/Dockerfile.gateway -t nodra-gateway .";
 return <main style={{minHeight:"100vh",background:"#07111f",color:"#eaf2ff",padding:"40px",fontFamily:"Inter,Arial"}}><div style={{maxWidth:900,margin:"0 auto"}}><Link href="/network" style={{color:"#8fb8ff"}}>← Dashboard</Link><p style={{color:"#6f8bab",marginTop:32}}>NODRA / INTEGRATIONS</p><h1>Connect your first agent</h1><p style={{color:"#91a5bf"}}>Register an AI agent, choose how it connects, create a scoped credential, then verify protection.</p><div style={{display:"flex",gap:8,margin:"28px 0"}}>{["Agent","Method","Credential","Install","Verify"].map((x,i)=><span key={x} style={{padding:"8px 12px",borderRadius:20,background:step>=i+1?"#123a68":"#111d2d",color:step>=i+1?"#fff":"#6f829a"}}>{i+1}. {x}</span>)}</div>
 {step===1&&<section><h2>Register agent</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Agent name" style={input}/><input value={agentId} onChange={e=>setAgentId(e.target.value)} placeholder="agent-id" style={input}/><button style={button} disabled={!name||!agentId} onClick={register}>Register agent →</button></section>}
 {step===2&&<section><h2>Choose integration</h2><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[["node","Node.js SDK"],["python","Python SDK"],["docker","Enterprise Gateway"]].map(([id,label])=><button key={id} onClick={()=>setMethod(id)} style={{...card,borderColor:method===id?"#3d9cff":"#26384d"}}><b>{label}</b><small style={{display:"block",marginTop:8,color:"#8ca2bc"}}>{id==="docker"?"Container / sidecar":"Native application integration"}</small></button>)}</div><button style={button} onClick={()=>setStep(3)}>Continue →</button></section>}
 {step===3&&<section><h2>Create credential</h2><p style={{color:"#91a5bf"}}>The secret is shown once. Store it in your server secret manager, never browser code.</p><button style={button} onClick={issue}>Generate secure credential</button></section>}
 {step===4&&<section><h2>Install Nodra</h2><label style={{color:"#8ca2bc"}}>Install</label><pre style={code}>{install}</pre><label style={{color:"#8ca2bc"}}>Credential — copy it now</label><pre style={code}>{credential}</pre><p style={{color:"#ffcb6b"}}>This secret will not be displayed again after you leave this page.</p><button style={button} onClick={()=>setStep(5)}>I stored the credential →</button></section>}
 {step===5&&<section><h2>{connected?"Nodra Protection Active":"Configure & verify protection"}</h2><p style={{color:connected?"#79e6a5":"#91a5bf"}}>{connected?"Signed runtime traffic has been verified and evidence is reaching Nodra.":"Send an authorization or event from your agent, then let Nodra verify the connection."}</p>{!connected?<><label style={{color:"#8ca2bc"}}>Allowed authority (comma separated)</label><input value={scope} onChange={e=>setScope(e.target.value)} placeholder="read, database:query" style={input}/><button style={button} onClick={saveAuthority}>Save authority</button><button style={{...button,marginLeft:10}} onClick={verify}>Test connection</button></>:<><div style={{...card,borderColor:"#1d8b55",marginTop:18}}><b>● PROTECTION ACTIVE</b><small style={{display:"block",marginTop:8,color:"#8ca2bc"}}>{name} · {agentId} · {method}</small></div><Link href="/activity" style={{...button,display:"inline-block",textDecoration:"none"}}>Open live activity →</Link></>}</section>}
 {message&&<p>{message}</p>}</div></main>
}
const input={display:"block",width:"100%",boxSizing:"border-box" as const,margin:"10px 0",padding:"14px",borderRadius:8,border:"1px solid #26384d",background:"#0c1929",color:"#fff"};
const button={marginTop:18,padding:"12px 18px",border:0,borderRadius:8,background:"#1677ff",color:"#fff",cursor:"pointer"};
const card={padding:22,textAlign:"left" as const,border:"1px solid",borderRadius:12,background:"#0c1929",color:"#fff",cursor:"pointer"};
const code={padding:16,borderRadius:8,background:"#030914",overflowX:"auto" as const,color:"#b9d7ff"};
