"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";

function NavIcon({name}:{name:string}){const p:any={Dashboard:<><path d="M4 11 12 4l8 7"/><path d="M6.5 10v9h11v-9"/></>,Network:<><circle cx="6" cy="6" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/><path d="M8 6h8M6 8v8M18 8v8M8 18h8"/></>,Agents:<><circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="3"/></>,Incidents:<><path d="M12 4 20 19H4L12 4Z"/></>,Activity:<><path d="M3 8c3-5 5 5 8 0s5 5 10 0M3 13c3-5 5 5 8 0s5 5 10 0M3 18c3-5 5 5 8 0s5 5 10 0"/></>,Policies:<><path d="m12 4 7 8-7 8-7-8 7-8Z"/></>,Credentials:<><path d="M5 7h15l-2 10H3L5 7Z"/></>,Containment:<><path d="m12 4 7 4v8l-7 4-7-4V8l7-4Z"/></>,Recovery:<><path d="M6 8a7 7 0 1 1-1 7"/><path d="M6 4v5H2"/></>,Reports:<><path d="M5 5h14v14H5zM8 5v14M11 5v14M14 5v14M17 5v14"/></>,Settings:<><circle cx="12" cy="12" r="3"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{p[name]}</svg>;}

const nav=[["/network","Dashboard"],["/network/map","Network"],["/agents","Agents"],["/incidents","Incidents"],["/activity","Activity"],["/policies","Policies"],["/credentials","Credentials"],["/containment","Containment"],["/recovery","Recovery"],["/reports","Reports"],["/settings","Settings"]];
const desc:any={map:"Visualize agent authority, trust relationships and propagation paths.",agents:"Manage and inspect protected AI agents.",incidents:"Detect, investigate and respond to security incidents.",activity:"Real-time security events and Flight Recorder evidence.",policies:"Inspect runtime authorization and enforcement evidence.",credentials:"Review scoped credential references and exposure state.",containment:"Isolate affected authority while healthy agents continue.",recovery:"Remediate incidents and assess safe restart.",reports:"Inspect forensic and security evidence reports.",settings:"Workspace and runtime security configuration."};

export function ProductSection({section}:{section:string}){
 const [state,setState]=useState<any>(null),[query,setQuery]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=()=>fetch("/api/laboratory/state",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setState).catch(()=>setState(null));
 useEffect(()=>{load()},[]);
 const act=async(label:string,url:string,body:any={})=>{setBusy(label);setMessage("");try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));setMessage(r.ok?label+" completed":j.error??label+" failed");await load()}catch{setMessage(label+" failed")}finally{setBusy("")}};
 const agents=state?.agents??[], incident=state?.incident, events=state?.events??[];
 const title=section==="map"?"Agent Network":section[0].toUpperCase()+section.slice(1);
 const matches=useMemo(()=>{const q=query.trim().toLowerCase();return q?agents.filter((a:any)=>[a.name,a.external_id,a.status].some(v=>String(v??"").toLowerCase().includes(q))):[]},[agents,query]);
 return <main className="lab"><aside className="sidebar"><Link className="labBrand exactBrand" href="/network" aria-label="Nodra dashboard"><img src="/nodra-logo.png" alt="Nodra — The Shield for Agentic AI"/></Link><nav className="sideNav">{nav.map(([href,label])=><Link key={href} className={(section==="map"?href==="/network/map":href==="/"+section)?"active":""} href={href}><i><NavIcon name={label}/></i><span>{label}</span></Link>)}</nav></aside><section className="labMain"><div className="commandTopbar"><label className="commandSearch"><span>⌕</span><input placeholder="Search agents, incidents, policies..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="topbarStatus"><span className="liveIndicator live"><i/> LIVE</span><span>V0.1</span></div></div><header className="labHeader"><div><p>NODRA / {title.toUpperCase()}</p><h1>{title}</h1><p className="dashboardSub">{desc[section]}</p></div></header>{query.trim()?<div className="workspaceSearch"><strong>Search results</strong>{matches.length?matches.map((a:any)=><Link key={a.id??a.external_id} href="/agents"><span>{a.name??a.external_id}</span><small>{String(a.status).replace("_"," ")}</small></Link>):<span>No matching agents</span>}</div>:null}<SectionBody section={section} state={state} act={act} busy={busy}/>{message?<div className="actionToast">{message}</div>:null}</section></main>
}
function SectionBody({section,state,act,busy}:{section:string;state:any;act:any;busy:string}){
 const agents=state?.agents??[], incident=state?.incident, events=state?.events??[], affected=state?.affected??[], actions=state?.containmentActions??[], recovery=state?.recovery;
 if(section==="map"){const by=(id:string)=>agents.find((a:any)=>a.external_id===id);return <div className="networkWorkspace"><section className="commandCard networkCanvas"><div className="commandTitle"><div><strong>Live Agent Network</strong><small>Authority, trust and propagation</small></div><span className="postureGood">LIVE</span></div><div className="topology"><svg viewBox="0 0 800 500" aria-hidden="true"><line x1="400" y1="250" x2="400" y2="70"/><line x1="400" y1="250" x2="160" y2="180"/><line x1="400" y1="250" x2="640" y2="180"/><line x1="400" y1="250" x2="400" y2="420"/></svg>{[["manager","center"],["research","north"],["finance","west"],["data","east"],["support","south"]].map(([id,pos])=>{const a=by(id);return <article key={id} className={"topologyNode "+pos}><span>{(a?.name??id)[0].toUpperCase()}</span><strong>{a?.name??id}</strong><small>{a?.status??"unknown"}</small></article>})}</div></section><aside className="networkRail"><div className="commandCard"><strong>Network Controls</strong><Link className="primaryAction" href="/agents">View agents</Link><Link href="/activity">Flight Recorder</Link><Link href="/reports">Forensic evidence</Link></div><div className="commandCard"><strong>Network Status</strong><p><b>{agents.filter((a:any)=>a.status==="healthy").length}/{agents.length}</b> healthy</p><p><b>{affected.length}</b> affected</p></div></aside></div>}
 if(section==="agents") return <section className="commandCard"><div className="commandTitle"><div><strong>Agent Inventory</strong><small>{agents.length} protected runtime identities</small></div></div><div className="sectionTable">{agents.map((a:any)=><div key={a.external_id}><strong>{a.name??a.external_id}</strong><span>{a.external_id} · {Array.isArray(a.authority_scope)?a.authority_scope.join(", "):a.authority_scope&&typeof a.authority_scope==="object"?Object.entries(a.authority_scope).map(([k,v])=>`${k}:${String(v)}`).join(", "):String(a.authority_scope??"scoped authority")}</span><b className="okText">{String(a.status).replace("_"," ")}</b></div>)}</div></section>;
 if(section==="incidents") return <section className="commandCard">{incident?<><div className="commandTitle"><div><strong>{incident.title??"Security incident"}</strong><small>{incident.severity} · {incident.state}</small></div><span className={incident.state==="resolved"?"postureGood":"incidentBadge"}>{incident.state}</span></div><div className="detailGrid"><div><small>Incident ID</small><code>{incident.id}</code></div><div><small>Affected entities</small><strong>{affected.length}</strong></div><div><small>Evidence events</small><strong>{events.filter((e:any)=>e.incident_id===incident.id).length}</strong></div></div><div className="buttonRow"><Link href="/activity">Inspect evidence</Link>{incident.state!=="resolved"?<button onClick={()=>act("Contain incident","/api/laboratory/contain",{incidentId:incident.id})} disabled={!!busy}>Contain incident</button>:null}</div></>:<div className="emptyIncident"><span>✓</span><strong>No active incidents</strong><p>New security incidents will appear here.</p></div>}</section>;
 if(section==="activity") return <section className="commandCard"><div className="commandTitle"><div><strong>Flight Recorder</strong><small>{events.length} observable security events</small></div><span className="recording">RECORDING</span></div><div className="sectionTable eventTable">{events.slice().reverse().map((e:any)=><div key={e.id}><strong>{e.event_type}</strong><span>{e.action??e.decision??"observed"}</span><small>#{e.sequence_no} · {e.occurred_at?new Date(e.occurred_at).toLocaleString():""}</small></div>)}</div></section>;
 if(section==="policies") return <section className="commandCard"><div className="commandTitle"><div><strong>Policy Gateway</strong><small>Observed runtime decisions</small></div></div><div className="detailGrid"><div><small>Policy decisions</small><strong>{events.filter((e:any)=>e.event_type==="policy-decision").length}</strong></div><div><small>Evidence integrity</small><strong>{state?.integrity?.valid?"Verified":"Check required"}</strong></div><div><small>Runtime mode</small><strong>Fail closed</strong></div></div><Link className="primaryAction inlineAction" href="/activity">Inspect policy evidence</Link></section>;
 if(section==="credentials") return <section className="commandCard"><div className="commandTitle"><div><strong>Credential Security</strong><small>Scoped authority evidence; secret values are never displayed.</small></div></div><div className="detailGrid"><div><small>Protected agents</small><strong>{agents.length}</strong></div><div><small>Credential-related evidence</small><strong>{events.filter((e:any)=>String(e.action??"").includes("credential")).length}</strong></div><div><small>Last remediation</small><strong>{state?.remediationEvidence?.length?"Evidence recorded":"None required"}</strong></div></div></section>;
 if(section==="containment") return <section className="commandCard"><div className="commandTitle"><div><strong>Containment Control</strong><small>Selective blast-radius enforcement</small></div><span className="postureGood">{incident?.state??"standby"}</span></div><div className="detailGrid"><div><small>Quarantined / restricted</small><strong>{agents.filter((a:any)=>a.status!=="healthy").length}</strong></div><div><small>Actions recorded</small><strong>{actions.length}</strong></div><div><small>Healthy</small><strong>{agents.filter((a:any)=>a.status==="healthy").length}</strong></div></div>{incident&&incident.state!=="resolved"?<button className="dangerAction" onClick={()=>act("Contain incident","/api/laboratory/contain",{incidentId:incident.id})} disabled={!!busy}>Contain affected branch</button>:<p className="quietState">No active containment action required.</p>}</section>;
 if(section==="recovery") return <section className="commandCard"><div className="commandTitle"><div><strong>Recovery Center</strong><small>Evidence-driven remediation and safe restart</small></div><span className="postureGood">{recovery?.safe_to_restart?"SAFE":"CONTROLLED"}</span></div>{recovery?<div className="sectionTable">{(recovery.steps??[]).map((s:any)=><div key={s.id}><strong>{s.title}</strong><span>{s.reason}</span><b>{s.status}</b></div>)}</div>:<p className="quietState">No recovery plan is currently required.</p>}{incident&&(incident.state==="contained"||incident.state==="recovering")&&!recovery?<button className="primaryAction" onClick={()=>act("Create recovery plan","/api/laboratory/recovery",{incidentId:incident.id})}>Create recovery plan</button>:null}</section>;
 if(section==="reports") return <section className="commandCard"><div className="commandTitle"><div><strong>Forensic Reports</strong><small>Evidence-backed investigation record</small></div></div><div className="detailGrid"><div><small>Timeline records</small><strong>{state?.forensicTimeline?.length??0}</strong></div><div><small>Chain integrity</small><strong>{state?.integrity?.valid?"Verified":"Unavailable"}</strong></div><div><small>Recorded events</small><strong>{events.length}</strong></div></div><Link className="primaryAction inlineAction" href="/activity">Open evidence timeline</Link></section>;
 return <section className="commandCard"><div className="commandTitle"><div><strong>Security Settings</strong><small>Runtime protection status</small></div></div><div className="settingsRows"><div><span>Evidence-chain verification</span><b>{state?.integrity?.valid?"Enabled":"Unavailable"}</b></div><div><span>Runtime agents</span><b>{agents.length} registered</b></div><div><span>Flight Recorder</span><b>Active</b></div></div></section>
}